logging.level.com.orange.clara.cloud.oauthregisterbroker: DEBUG

---
endpoints:
  env:
    keys-to-sanitize: jdbcurl,uri,DATABASE_URL,username,url,password,key_id,access_key,VCAP_SERVICES,encryption_key
management:
  contextPath: /admin
spring:
  jpa:
    hibernate:
      ddl-auto: none
security:
  require-ssl: ${use.ssl:false}
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: ${CF_TARGET:http://fake.uaa.com}/oauth/token
      userAuthorizationUri: ${CF_TARGET:http://fake.uaa.com}/oauth/authorize
      clientAuthenticationScheme: header
      scope:
      - openid
      - cloud_controller_service_permissions.read
    resource:
      userInfoUri: ${CF_TARGET:http://fake.uaa.com}/userinfo
      preferTokenInfo: false
